{% set version = "0.0.9" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-rapidatetime
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/RApiDatetime_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/RApiDatetime/RApiDatetime_{{ version }}.tar.gz
  sha256: fe4ee608ce7568994125323abbe0d07fc462651a4e057a7e19267f78d1ae0de9

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
  # Checking windows to see if it passes. Uncomment the line if it fails.
  # skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('RApiDatetime')"           # [not win]
    - "\"%R%\" -e \"library('RApiDatetime')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=RApiDatetime
  license: GPL-2.0-or-later
  summary: "Access to the C-level R date and datetime code is provided for C-level API use by other packages via registration of native functions. Client packages simply include a single header 'RApiDatetime.h' provided by this package, and also 'import' it.  The R Core group is the original author of the code made available
    with slight modifications by this package. "
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - philip-khor
